"""nullable user email.

Revision ID: 873b1ff0e426
Revises: 28edff1ebd7c
Create Date: 2026-05-22 10:00:00.460252

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "873b1ff0e426"
down_revision = "28edff1ebd7c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=254), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=254), nullable=False
    )
    # ### end Alembic commands ###
