"""add business_profile to organizations.

Revision ID: 28edff1ebd7c
Revises: a43fb9e9044e
Create Date: 2026-05-22 09:41:05.787364

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "28edff1ebd7c"
down_revision = "a43fb9e9044e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "business_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "business_profile")
    # ### end Alembic commands ###
