"""add_stripe_fields_to_organizations.

Revision ID: a43fb9e9044e
Revises: 7b43db182a8f
Create Date: 2026-05-22 00:09:21.940789

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a43fb9e9044e"
down_revision = "7b43db182a8f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("stripe_customer_id", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "organizations",
        sa.Column("stripe_subscription_id", sa.String(length=128), nullable=True),
    )
    op.create_unique_constraint(None, "organizations", ["stripe_customer_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organizations", type_="unique")
    op.drop_column("organizations", "stripe_subscription_id")
    op.drop_column("organizations", "stripe_customer_id")
    # ### end Alembic commands ###
