"""add_organizations_org_scope_integrations_investigations.

Revision ID: 7b43db182a8f
Revises: 36e10c042f7f
Create Date: 2026-05-21 23:37:01.358469

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b43db182a8f"
down_revision = "36e10c042f7f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("owner_auth0_id", sa.String(length=128), nullable=True),
        sa.Column("plan", sa.String(length=20), server_default="free", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["owner_auth0_id"], ["users.auth0_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "organization_invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column(
            "role", sa.String(length=20), server_default="member", nullable=False
        ),
        sa.Column("invited_by", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["invited_by"], ["users.auth0_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "organization_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_auth0_id", sa.String(length=128), nullable=False),
        sa.Column(
            "role", sa.String(length=20), server_default="member", nullable=False
        ),
        sa.Column("invited_by", sa.String(length=128), nullable=True),
        sa.Column(
            "joined_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"], ["users.auth0_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_auth0_id"], ["users.auth0_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "user_auth0_id", name="org_members_org_user_key"),
    )
    op.add_column("integrations", sa.Column("org_id", sa.UUID(), nullable=False))
    op.drop_constraint(
        op.f("integrations_user_auth0_id_tool_key"), "integrations", type_="unique"
    )
    op.create_unique_constraint(
        "integrations_org_id_tool_key", "integrations", ["org_id", "tool"]
    )
    op.drop_constraint(
        op.f("integrations_user_auth0_id_fkey"), "integrations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "integrations", "organizations", ["org_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("integrations", "user_auth0_id")
    op.add_column("investigations", sa.Column("org_id", sa.UUID(), nullable=False))
    op.add_column(
        "investigations", sa.Column("created_by", sa.String(length=128), nullable=False)
    )
    op.drop_constraint(
        op.f("investigations_user_auth0_id_fkey"), "investigations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "investigations", "organizations", ["org_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "investigations",
        "users",
        ["created_by"],
        ["auth0_id"],
        ondelete="CASCADE",
    )
    op.drop_column("investigations", "user_auth0_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "investigations",
        sa.Column(
            "user_auth0_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "investigations", type_="foreignkey")
    op.drop_constraint(None, "investigations", type_="foreignkey")
    op.create_foreign_key(
        op.f("investigations_user_auth0_id_fkey"),
        "investigations",
        "users",
        ["user_auth0_id"],
        ["auth0_id"],
        ondelete="CASCADE",
    )
    op.drop_column("investigations", "created_by")
    op.drop_column("investigations", "org_id")
    op.add_column(
        "integrations",
        sa.Column(
            "user_auth0_id", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "integrations", type_="foreignkey")
    op.create_foreign_key(
        op.f("integrations_user_auth0_id_fkey"),
        "integrations",
        "users",
        ["user_auth0_id"],
        ["auth0_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("integrations_org_id_tool_key", "integrations", type_="unique")
    op.create_unique_constraint(
        op.f("integrations_user_auth0_id_tool_key"),
        "integrations",
        ["user_auth0_id", "tool"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("integrations", "org_id")
    op.drop_table("organization_members")
    op.drop_table("organization_invites")
    op.drop_table("organizations")
    # ### end Alembic commands ###
