"""Report DAO."""

from __future__ import annotations

import uuid
from datetime import UTC, date, datetime
from typing import Any

from fastapi import Depends
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from api.db.dependencies import get_db_session
from api.db.models.report_model import Report


class ReportDAO:
    """Provides access to the reports table."""

    def __init__(self, session: AsyncSession = Depends(get_db_session)) -> None:
        self.session = session

    async def create(
        self,
        org_id: uuid.UUID,
        created_by: str,
        date_from: date,
        date_to: date,
        result: dict[str, Any],
        sources_used: list[str],
        ai_model: str,
    ) -> Report:
        """Persist a completed report.

        :param org_id: Organisation UUID.
        :param created_by: Auth0 ID of the user who generated the report.
        :param date_from: Start of the report period.
        :param date_to: End of the report period.
        :param result: Structured result dict from the AI agent.
        :param sources_used: List of integration names used.
        :param ai_model: LiteLLM model identifier used.
        :return: The saved Report row.
        """
        report = Report(
            org_id=org_id,
            created_by=created_by,
            date_from=date_from,
            date_to=date_to,
            result=result,
            sources_used=sources_used,
            ai_model=ai_model,
        )
        self.session.add(report)
        await self.session.flush()
        return report

    async def count_this_month(self, org_id: uuid.UUID) -> int:
        """Count reports generated by this org in the current calendar month.

        :param org_id: Organisation UUID.
        :return: Count of reports since the start of this month.
        """
        now = datetime.now(tz=UTC)
        month_start = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0, tzinfo=None)
        result = await self.session.execute(
            select(func.count()).where(
                Report.org_id == org_id,
                Report.created_at >= month_start,
            )
        )
        return result.scalar_one()

    async def list_for_org(
        self,
        org_id: uuid.UUID,
        limit: int = 20,
        offset: int = 0,
    ) -> list[Report]:
        """Return paginated reports for an organisation, newest first.

        :param org_id: Organisation UUID.
        :param limit: Maximum rows to return.
        :param offset: Row offset for pagination.
        :return: List of Report rows.
        """
        result = await self.session.execute(
            select(Report)
            .where(Report.org_id == org_id)
            .order_by(Report.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        return list(result.scalars().all())

    async def get_by_id(
        self, report_id: uuid.UUID, org_id: uuid.UUID
    ) -> Report | None:
        """Fetch a single report, scoped to the organisation.

        :param report_id: UUID primary key.
        :param org_id: Organisation UUID (ownership check).
        :return: Report if found, else None.
        """
        result = await self.session.execute(
            select(Report).where(
                Report.id == report_id,
                Report.org_id == org_id,
            )
        )
        return result.scalar_one_or_none()
